rails generate rspec:model anonymous_profile
rails generate rspec:model block
rails generate rspec:model conversation_message
rails generate rspec:model conversation_user
rails generate rspec:model conversation
rails generate rspec:model credit_history
rails generate rspec:model feed
rails generate rspec:model follow
rails generate rspec:model friend
rails generate rspec:model grapevine_message
rails generate rspec:model group_user
rails generate rspec:model group
rails generate rspec:model notification
rails generate rspec:model post
rails generate rspec:model referral
rails generate rspec:model report
rails generate rspec:model topic
rails generate rspec:model post
