# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92138373fddba3e489d8fd3c4e030a28e86a780ec78866192b10a589485f88c16fa7feeeae5536e7f7dc3855bc1594f21ff9cae2db7294d9245fa90df1354b4d

test:
  secret_key_base: be090bb0b3d3d2fb1d50df23244f607affc12e1fc5aaf598286dae4cb2192cfbd08179121b5159be49e5cec41c9029822056e4d66912476a5d32a08ac3782403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
