require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ConversationUsersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ConversationUser. As you add validations to ConversationUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConversationUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all conversation_users as @conversation_users" do
      conversation_user = ConversationUser.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:conversation_users)).to eq([conversation_user])
    end
  end

  describe "GET show" do
    it "assigns the requested conversation_user as @conversation_user" do
      conversation_user = ConversationUser.create! valid_attributes
      get :show, {:id => conversation_user.to_param}, valid_session
      expect(assigns(:conversation_user)).to eq(conversation_user)
    end
  end

  describe "GET edit" do
    it "assigns the requested conversation_user as @conversation_user" do
      conversation_user = ConversationUser.create! valid_attributes
      get :edit, {:id => conversation_user.to_param}, valid_session
      expect(assigns(:conversation_user)).to eq(conversation_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConversationUser" do
        expect {
          post :create, {:conversation_user => valid_attributes}, valid_session
        }.to change(ConversationUser, :count).by(1)
      end

      it "assigns a newly created conversation_user as @conversation_user" do
        post :create, {:conversation_user => valid_attributes}, valid_session
        expect(assigns(:conversation_user)).to be_a(ConversationUser)
        expect(assigns(:conversation_user)).to be_persisted
      end

      it "redirects to the created conversation_user" do
        post :create, {:conversation_user => valid_attributes}, valid_session
        expect(response).to redirect_to(ConversationUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conversation_user as @conversation_user" do
        post :create, {:conversation_user => invalid_attributes}, valid_session
        expect(assigns(:conversation_user)).to be_a_new(ConversationUser)
      end

      it "re-renders the 'new' template" do
        post :create, {:conversation_user => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested conversation_user" do
        conversation_user = ConversationUser.create! valid_attributes
        put :update, {:id => conversation_user.to_param, :conversation_user => new_attributes}, valid_session
        conversation_user.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested conversation_user as @conversation_user" do
        conversation_user = ConversationUser.create! valid_attributes
        put :update, {:id => conversation_user.to_param, :conversation_user => valid_attributes}, valid_session
        expect(assigns(:conversation_user)).to eq(conversation_user)
      end

      it "redirects to the conversation_user" do
        conversation_user = ConversationUser.create! valid_attributes
        put :update, {:id => conversation_user.to_param, :conversation_user => valid_attributes}, valid_session
        expect(response).to redirect_to(conversation_user)
      end
    end

    describe "with invalid params" do
      it "assigns the conversation_user as @conversation_user" do
        conversation_user = ConversationUser.create! valid_attributes
        put :update, {:id => conversation_user.to_param, :conversation_user => invalid_attributes}, valid_session
        expect(assigns(:conversation_user)).to eq(conversation_user)
      end

      it "re-renders the 'edit' template" do
        conversation_user = ConversationUser.create! valid_attributes
        put :update, {:id => conversation_user.to_param, :conversation_user => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conversation_user" do
      conversation_user = ConversationUser.create! valid_attributes
      expect {
        delete :destroy, {:id => conversation_user.to_param}, valid_session
      }.to change(ConversationUser, :count).by(-1)
    end

    it "redirects to the conversation_users list" do
      conversation_user = ConversationUser.create! valid_attributes
      delete :destroy, {:id => conversation_user.to_param}, valid_session
      expect(response).to redirect_to(conversation_users_url)
    end
  end

end
